#production:
#  features:
#   image_templates: true
#   cloud_upload: false
#   cloud_upload_azure: false
#   bootstrap: false
#   kiwi_image_editor: false

development:
  features:
    kiwi_image_editor: true
    cloud_upload: true
    cloud_upload_azure: true

test:
  features:
    kiwi_image_editor: true
    cloud_upload: true
    cloud_upload_azure: true

beta:
  features:
    kiwi_image_editor: true
    cloud_upload: true
    cloud_upload_azure: true
    bootstrap: true
